# -*- coding: utf-8 -*-
"""Copia de Gray-Scott_revisado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Z8nfGX8FRgW1MyqPDeK1tFIeM_dtsXr
"""

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import matplotlib.pyplot as plt

# Parámetros del modelo Gray-Scott
Du, Dv = 0.16, 0.08
# F, k = 0.029, 0.057 #laberinto
# F, k = 0.060, 0.062
F, k = 0.03, 0.06 #solitons

# Dominio y discretización
# Nx, Ny = 3, 3 nodos internos. La malla real es (Nx+1)x(Ny+1)
NN=128
Nx, Ny = NN, NN
Lx, Ly = 100.0, 100.0
dx = Lx / (Nx + 1) # h = 1/(3+1) = 1/4
dy = Ly / (Ny + 1) # Usamos Nx+1 en lugar de Nx-1 para h

# Paso temporal (IMEX permite mayor Δt)
# dt = 1e-2
dt = 0.5
# steps = 500
steps = 10000

# Dimension total del sistema
N = Nx * Ny

# --------------------------------------------------------------------------
# 1. Construcción de la matriz Laplaciano periódica L
# --------------------------------------------------------------------------

# a) Matriz T de 1D (Bloque de conectividad en x)
diag_T = -4.0 * np.ones(Nx)
off_T = np.ones(Nx - 1)

# Creamos la parte tridiagonal
T = sp.diags([off_T, diag_T, off_T], [-1, 0, 1], shape=(Nx, Nx), format='csr')

# Añadimos las conexiones de periodicidad en x (las esquinas del bloque T)
T[0, Nx - 1] = 1.0  # Conexión U_1 con U_Nx
T[Nx - 1, 0] = 1.0  # Conexión U_Nx con U_1

# b) Ensamblaje de la matriz L total (circulante de bloques)
# L tiene la estructura de bloques circulantes: [T, I, I; I, T, I; I, I, T]

I_block = sp.eye(Nx) # Bloque Identidad 3x3

# Se construyen las bandas principales (T, I, I) y (I, T, I)
# L_main contiene la matriz tridiagonal de bloques (Dirichlet en Y)
L_main = sp.block_diag([T] * Ny, format='csr') # Bloques T en la diagonal principal
L_off_diag = sp.diags([np.ones(N - Nx), np.ones(N - Nx)], [-Nx, Nx], shape=(N, N), format='csr') # Bandas +/- Nx (conexiones internas en Y)

# Las bandas off_diag son solo unos. Deben ser bloques I_block.
# La manera correcta es usar L_block_diag y sumar los I_block fuera de la diagonal.

# Construcción usando una matriz CSR vacía para mayor control:
L = sp.csr_matrix((N, N))

for i in range(Ny):
    # Conexiones internas en Y (L_i, i+1 y L_i+1, i)
    if i < Ny - 1:
        # L[i, i+1] = I
        L[i * Nx : (i + 1) * Nx, (i + 1) * Nx : (i + 2) * Nx] = I_block
        # L[i+1, i] = I
        L[(i + 1) * Nx : (i + 2) * Nx, i * Nx : (i + 1) * Nx] = I_block

    # Conexiones periódicas en Y (L_0, Ny-1 y L_Ny-1, 0)
    if i == 0:
        # L[0, Ny-1] = I
        L[0 : Nx, (Ny - 1) * Nx : N] = I_block
    if i == Ny - 1:
        # L[Ny-1, 0] = I
        L[(Ny - 1) * Nx : N, 0 : Nx] = I_block

# L_final = L_horizontal (T blocks) + L_vertical (I blocks)
L = L + L_main

# El Laplaciano Discreto L incluye el factor 1/h^2
L /= (dx * dy)
# print("Matriz L (Periódica):")
# print(L.todense())
# Verificación de la matriz A*h^2 (si descomentas verás la matriz deducida)
# print("Matriz L * h^2 (Periódica, verificacion):")
# print(L.todense() * (dx * dy))


# --------------------------------------------------------------------------
# 2. Inicialización y simulación IMEX
# --------------------------------------------------------------------------

# Inicialización
u = np.ones((Nx, Ny))
v = np.zeros((Nx, Ny))
# np.random.seed(0)
# u += 0.05 * np.random.rand(Nx, Ny)
# v += 0.05 * np.random.rand(Nx, Ny)


# Centro del dominio
# mid = Nx // 2
# r = 10 # radio de la perturbación
# u[mid-r:mid+r, mid-r:mid+r] = 0.50
# v[mid-r:mid+r, mid-r:mid+r] = 0.25


# Definimos cuántas semillas queremos
num_semillas = 15
r = 4  # Radio de cada semilla

for _ in range(num_semillas):
    # Posiciones aleatorias para las semillas
    cx, cy = np.random.randint(r, Nx-r), np.random.randint(r, Ny-r)

    # Aplicamos la perturbación en un área pequeña
    u[cx-r:cx+r, cy-r:cy+r] = 0.50
    v[cx-r:cx+r, cy-r:cy+r] = 0.25

# Añadir un ruido de fondo muy tenue para romper la simetría
u += 0.02 * np.random.standard_normal((Nx, Ny))
v += 0.02 * np.random.standard_normal((Nx, Ny))


# Matrices IMEX A_u y A_v (incluyen el término implícito del Laplaciano)
I = sp.eye(N)
A_u = I - dt * Du * L
A_v = I - dt * Dv * L

# Funciones para convertir entre 2D y 1D
def flatten(Z):
    return Z.ravel()

def reshape(Z):
    return Z.reshape((Nx, Ny))

# Simulación IMEX con condiciones periódicas
snapshots = {}
for n in range(steps):
    # Parte explícita (reacción) R^k
    R_u = -u * v**2 + F * (1 - u)
    R_v = u * v**2 - (F + k) * v

    # Lado Derecho (RHS) F^k = U^k + dt * R^k
    RHS_u = flatten(u + dt * R_u)
    RHS_v = flatten(v + dt * R_v)

    # Resolver sistemas lineales: A * U^(k+1) = F^k
    # Utilizamos spla.spsolve para matrices dispersas.
    u_new = spla.spsolve(A_u, RHS_u)
    v_new = spla.spsolve(A_v, RHS_v)

    u = reshape(u_new)
    v = reshape(v_new)

    if n in [10, 100, steps - 1]:
        snapshots[n] = (u.copy(), v.copy())

# --------------------------------------------------------------------------
# 3. Visualización
# --------------------------------------------------------------------------
fig, axes = plt.subplots(len(snapshots), 2, figsize=(8, 8))
if len(snapshots) == 1: # Manejo del caso de una sola fila de subplots
    axes = np.expand_dims(axes, axis=0)

for idx, (t, (u_snap, v_snap)) in enumerate(snapshots.items()):
    ax1 = axes[idx, 0]
    ax2 = axes[idx, 1]

    # Graficar U
    im1 = ax1.imshow(u_snap, cmap='viridis', origin='lower', extent=[0, Lx, 0, Ly])
    ax1.set_title(f'u en t={t * dt:.2f}')

    # Graficar V
    im2 = ax2.imshow(v_snap, cmap='plasma', origin='lower', extent=[0, Lx, 0, Ly])
    ax2.set_title(f'v en t={t * dt:.2f}')

# Configuración de barras de color
fig.subplots_adjust(right=0.8)
cbar_ax1 = fig.add_axes([0.83, 0.15, 0.03, 0.7])
cbar_ax2 = fig.add_axes([0.88, 0.15, 0.03, 0.7])

# Añadir colorbars de forma separada para mejor control
plt.colorbar(im1, cax=cbar_ax1, label='Concentración U')
plt.colorbar(im2, cax=cbar_ax2, label='Concentración V')

plt.tight_layout(rect=[0, 0, 0.8, 1])
plt.savefig('patrones_IMEX_periodicas_corregido.png')
print('Simulación IMEX con condiciones periódicas completada. Imagen guardada como patrones_IMEX_periodicas_corregido.png')

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML # ¡Importante para Colab!

# --------------------------------------------------------------------------
# 1. Parámetros del modelo (Configuración para LABERINTOS) - INTACTO
# --------------------------------------------------------------------------
Du, Dv = 0.16, 0.08
F, k = 0.029, 0.057
# F, k = 0.03, 0.06
NN = 128
Nx, Ny = NN, NN
Lx, Ly = 100.0, 100.0
dx, dy = Lx / Nx, Ly / Ny

dt = 0.5
steps = 10000

# --------------------------------------------------------------------------
# 2. Construcción del Laplaciano 2D con condiciones periódicas - INTACTO
# --------------------------------------------------------------------------
def laplacian_1d_periodic(N, h):
    main_diag = -2.0 * np.ones(N)
    off_diag = np.ones(N - 1)
    L = sp.diags([off_diag, main_diag, off_diag], [-1, 0, 1], shape=(N, N), format='csc')
    L[0, N-1] = 1.0
    L[N-1, 0] = 1.0
    return L / (h**2)

Lx_matrix = laplacian_1d_periodic(Nx, dx)
Ly_matrix = laplacian_1d_periodic(Ny, dy)
L = sp.kronsum(Ly_matrix, Lx_matrix, format='csc')

# --------------------------------------------------------------------------
# 3. Inicialización y pre-factorización IMEX - INTACTO
# --------------------------------------------------------------------------
u = np.ones((Nx, Ny))
v = np.zeros((Nx, Ny))

#central
# r = 10
# u[Nx//2-r:Nx//2+r, Ny//2-r:Ny//2+r] = 0.50
# v[Nx//2-r:Nx//2+r, Ny//2-r:Ny//2+r] = 0.25
# u += 0.01 * np.random.standard_normal((Nx, Ny))
# v += 0.01 * np.random.standard_normal((Nx, Ny))


#varios lugares
# Definimos cuántas semillas queremos
num_semillas = 15
r = 4  # Radio de cada semilla

for _ in range(num_semillas):
    # Posiciones aleatorias para las semillas
    cx, cy = np.random.randint(r, Nx-r), np.random.randint(r, Ny-r)

    # Aplicamos la perturbación en un área pequeña
    u[cx-r:cx+r, cy-r:cy+r] = 0.50
    v[cx-r:cx+r, cy-r:cy+r] = 0.25

# Añadir un ruido de fondo muy tenue para romper la simetría
u += 0.02 * np.random.standard_normal((Nx, Ny))
v += 0.02 * np.random.standard_normal((Nx, Ny))

I_mat = sp.eye(Nx * Ny, format='csc')
A_u = I_mat - dt * Du * L
A_v = I_mat - dt * Dv * L

print("Factorizando matrices...")
solve_u = spla.factorized(A_u)
solve_v = spla.factorized(A_v)

# --------------------------------------------------------------------------
# 4. Simulación y Captura de Cuadros para el Video (INTACTO)
# --------------------------------------------------------------------------
print(f"Calculando simulación...")
frames_list = []
n_vids = 100      # Número de cuadros que tendrá el video final
snap = steps // n_vids # Cada cuántos pasos de simulación guardar un cuadro

for n in range(steps):
    # --- TU LÓGICA DE CÁLCULO ORIGINAL (INTACTA) ---
    uv2 = u * (v**2)
    rhs_u = (u + dt * (-uv2 + F * (1.0 - u))).flatten()
    rhs_v = (v + dt * (uv2 - (F + k) * v)).flatten()

    u = solve_u(rhs_u).reshape((Nx, Ny))
    v = solve_v(rhs_v).reshape((Ny, Nx)) # Corregido para asegurar la forma Nx, Ny
    # ^^^^^ Asegúrate de que esto sea .reshape((Nx, Ny)) ^^^^^^

    # Guardamos una "foto" del estado cada cierto tiempo
    if n % snap == 0:
        frames_list.append(u.copy())
        if n % (steps // 10) == 0: # Imprime progreso cada 10%
            print(f"Progreso de simulación: {n/steps*100:.0f}%")

# --------------------------------------------------------------------------
# 5. Generación del Reproductor de Video (Específico para Colab)
# --------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(6, 6))
img = ax.imshow(frames_list[0], cmap='magma', extent=[0, Lx, 0, Ly], origin='lower')
ax.axis('off')
ax.set_title("Evolución de Patrón de Laberinto (Gray-Scott)")

def animate(i):
    img.set_array(frames_list[i])
    # Se ajusta el título para mostrar el tiempo real o el paso de simulación
    ax.set_title(f"Paso {i * snap} / {steps} (t={i * snap * dt:.1f})")
    return [img]

print("Preparando reproductor de video interactivo...")
# ani = FuncAnimation(fig, animate, frames=len(frames_list), interval=50, blit=True)
ani = FuncAnimation(fig, animate, frames=len(frames_list), interval=50) # blit=True puede dar problemas en Colab

# ¡Esta es la línea clave para que aparezca el reproductor en Colab!
video_widget = HTML(ani.to_jshtml())
plt.close(fig) # Cierra la figura de Matplotlib para no mostrarla dos veces

# Muestra el widget de video
video_widget

